# Generated by Django 3.1.6 on 2021-02-13 01:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_alllisting_bid_closebid_comment_listing_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alllisting',
            name='listingId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_id', to='auctions.listing'),
        ),
    ]
