# Generated by Django 3.1.6 on 2021-02-16 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210215_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllisting',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
