# Generated by Django 3.1.6 on 2021-02-18 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_auto_20210217_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='alllisting',
            name='category',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
