# Generated by Django 3.1.6 on 2021-02-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_alllisting_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
