# Generated by Django 3.1.6 on 2021-02-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_auto_20210218_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='bid_currency',
        ),
        migrations.RemoveField(
            model_name='closebid',
            name='winprice_currency',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price_currency',
        ),
        migrations.AlterField(
            model_name='bid',
            name='bid',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='closebid',
            name='winprice',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
    ]
