# Generated by Django 3.1.6 on 2021-02-18 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210218_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='time',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
